import Providers from "@/components/ui/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Nav from "@/components/nav"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hodo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body >
          <Nav /> 
          <div className={inter.className}>
           <Providers>{children}</Providers>
          </div>
        </body>
      </ClerkProvider>
    </html>
  );
}
